export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';

// FOR LOGIN

export const LOGIN = 'LOGIN';
export const LOGIN_ASYNC = 'LOGIN_ASYNC';

// FOR REGISTER

export const REGISTER = 'REGISTER';
export const REGISTER_ASYNC = 'REGISTER_ASYNC';

// FOR FETCHING ALL PRODUCTS

export const ALL_PRODUCTS_ASYNC = 'ALL_PRODUCTS_ASYNC';
export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const CLEAR_STATE = 'CLEAR_STATE';

// FETCHING COLOR AND CATEGORY

export const GET_CATEGORY_ASYNC = 'GET_CATEGORY_ASYNC';
export const GET_COLOR_ASYNC = 'GET_COLOR_ASYNC';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_COLOR = 'GET_COLOR';

// ADDING AND FETCHING FROM CART

export const ADD_T0_CART_ASYNC = 'ADD_T0_CART_ASYNC';
export const ADD_T0_CART = 'ADD_T0_CART';
export const CLEAR_ADDED_TO_CART = 'CLEAR_ADDED_TO_CART';
export const GET_CART_ASYNC = 'GET_CART_ASYNC';
export const GET_CART = 'GET_CART';

//UPDATING CART

export const UPDATE_QUANTITY_ASYNC = 'UPDATE_QUANTITY_ASYNC';
export const DELETE_FROM_CART_ASYNC = 'DELETE_FROM_CART_ASYNC';

// ADDRESSES

export const GET_ADDRESS_ASYNC = 'GET_ADDRESS_ASYNC';
export const GET_ADDRESS = 'GET_ADDRESS';
export const ADD_ADDRESS_ASYNC = 'ADD_ADDRESS_ASYNC';
export const DELETE_ADDRESS_ASYNC = 'DELETE_ADDRESS_ASYNC';
export const EDIT_ADDRESS_ASYNC = 'EDIT_ADDRESS_ASYNC';

// ORDERS

export const PLACE_ORDER_ASYNC = 'PLACE_ORDER_ASYNC';
export const VIEW_ORDERS_ASYNC = 'VIEW_ORDERS_ASYNC';
export const VIEW_ORDERS = 'VIEW_ORDERS';
